name: Build DLL

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # 1. 不需要 vcpkg，系统已带 glew + OpenGL
    - name: Configure & Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'ninja-system'
        buildPreset: 'ninja-system-rel'

    # 2. 上传产物
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: InfiniteGUI-DLL-x64
        path: |
          build/Release/InfiniteGUI-DLL.dll
